workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      codemagic:
        distribution_type: ad-hoc
    environment:
      ios_signing:
        distribution_type: ad-hoc
        bundle_identifier: com.example.app
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com 