workflows:
  ios-build:
    name: iOS Build Turathna
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        MATCH_PASSWORD: $MATCH_PASSWORD
        MATCH_GIT_URL: $MATCH_GIT_URL
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
          cd ios
          pod deintegrate
          pod cache clean --all
          cd ..
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Run tests
        script: |
          flutter test
      - name: Setup code signing
        script: |
          cd ios
          fastlane match development --readonly
          fastlane match appstore --readonly
          cd ..
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --build-name=$CM_BUILD_NUMBER \
            --build-number=$CM_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - $EMAIL_RECIPIENT
      slack:
        channel: '#builds'
        notify_on_build_start: true
    caching:
      paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
