workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      codemagic:
        distribution_type: ad-hoc
    environment:
      ios_signing:
        distribution_type: ad-hoc
        bundle_identifier: com.example.app
        team_id: YOUR_TEAM_ID # Replace with your Apple Developer Team ID
        provisioning_profile_specifier: YOUR_PROVISIONING_PROFILE # Replace with your provisioning profile name
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
      app_store_connect:
        submit_for_review: false
        beta_groups: []

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux
    environment:
      android_signing:
        keystore_reference: android_keystore
      flutter: stable
      groups:
        - google_credentials
    scripts:
      - name: Clean project
        script: |
          flutter clean
          cd android
          ./gradlew clean
          cd ..
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --verbose
      - name: List build outputs
        script: |
          find build -name "*.apk"
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - user@example.com

  build-apk:
    name: Build APK (Flutter + Kotlin DSL)
    environment:
      flutter: stable
      xcode: none
      android_signing:
        keystore_reference: my-keystore
      vars:
        JAVA_VERSION: "17"
        ANDROID_NDK_VERSION: "25.1.8937393"
    scripts:
      - name: 📦 Get Flutter packages
        script: flutter pub get

      - name: 🛠️ Clean build cache
        script: flutter clean

      - name: 📁 Make Gradle executable
        script: chmod +x android/gradlew

      - name: 🔧 Build APK in release mode
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk 