name: turathna
description: "Turathna - Discover Algeria's Cultural Heritage"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.8
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  video_player: ^2.8.1
  flutter_lints: ^5.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  firebase_core_web: ^2.10.0
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  cross_file: ^0.3.3+8
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.4.0
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  youtube_player_flutter: ^9.0.3
  file_picker: ^10.1.9  # ✅ ajout de la version compatible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bordj_logo.jpg
    - assets/images/bordj1.jpg
    - assets/images/bordj2.jpg
    - assets/images/bordj3.jpg
    - assets/images/bordj4.jpg
    - assets/images/bordj5.jpg
    - assets/images/page1.jpg
    - assets/images/iconapp.jpg
    - assets/lang/en.json
    - assets/lang/fr.json
    - assets/lang/ar.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconapp.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
